name: CloudEQ_intro(Workflow_Name_2)
on:

  push:
    branches: [ "main" ]
jobs:
  
  job-1:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3


      - name: Run a one-line script
        run: echo CloudEQ is Provide the software services.